name: coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@91054c3b9dc15fdc6a2f45be47405d891e672ef0
        with:
          tools-deps: '1.10.1.727'
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: coverage-m2-${{ hashFiles('deps.edn') }}-v1
      - name: Run cloverage
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          make coverage
          bash <(curl -s https://codecov.io/bash)
