name: test
on: [push]

jobs:
  test-clj:
    strategy:
      matrix:
        java: ['8', '11', '14', '15']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - run: java -version
      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.3.822'
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: test-m2-${{ hashFiles('deps.edn') }}-v1
      - name: run test
        run: make test-clj

  test-cljs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.3.822'
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: test-m2-${{ hashFiles('deps.edn') }}-v1
      - run: make test-cljs
